In [2]:


import numpy as np

In [3]:
q1 = np.array([
    [200,220,250],
    [150,180,210],
    [300,330,360]
])

q2 = np.array([
    [209,231,259],
    [155,192,222],
    [310,340,375]
])

In [4]:
q1 + q2

array([[409, 451, 509],
       [305, 372, 432],
       [610, 670, 735]])

In [5]:
q2-q1

array([[ 9, 11,  9],
       [ 5, 12, 12],
       [10, 10, 15]])

In [6]:
(q2-q1)*100/q1

array([[4.5       , 5.        , 3.6       ],
       [3.33333333, 6.66666667, 5.71428571],
       [3.33333333, 3.03030303, 4.16666667]])

In [10]:
prices = np.array([
    [10,12,11],
    [8,9,10],
    [15,16,17]
])
prices

array([[10, 12, 11],
       [ 8,  9, 10],
       [15, 16, 17]])

In [12]:
q1_revenue = q1 * prices
q1_revenue

array([[2000, 2640, 2750],
       [1200, 1620, 2100],
       [4500, 5280, 6120]])

In [17]:
q1_discount = q1_revenue*0.2
q1_discount

array([[ 400.,  528.,  550.],
       [ 240.,  324.,  420.],
       [ 900., 1056., 1224.]])

In [19]:
net_revenue = q1_revenue - q1_discount
net_revenue

array([[1600., 2112., 2200.],
       [ 960., 1296., 1680.],
       [3600., 4224., 4896.]])

In [20]:
np.sum(net_revenue)

np.float64(22568.0)

In [24]:
feature = np.array([
    [2000, 3], #house 1
    [1800,2]   #house 2
])

weight = np.array([150, 50000 ])
np.dot(feature, weight)

array([450000, 370000])