Introduction and benefits of NumPy

In [1]:
from platform import version

import numpy as np
from adodbapi.ado_consts import adArray
from unicodedata import numeric

using numpy np.array takes less storage as compare to normal list function

In [4]:
charr = np.array([1,2,3,33,3])
charr

array([ 1,  2,  3, 33,  3])

In [3]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [8]:
python_list = list(range(100))
python_list[:4]

[0, 1, 2, 3]

In [9]:
import sys
sys.getsizeof(python_list[0])*len(python_list)

2800

In [11]:
num = np.arange(100)
num[:5]

array([0, 1, 2, 3, 4])

In [13]:
num.nbytes

800

In [4]:
a = np.array([2,3,4,44,4])
a

array([ 2,  3,  4, 44,  4])

In [8]:
import time

In [43]:
size = 10000000

L1 = list(range(size))
L2 = list(range(size))

start_time = time.time()
L3 = [x+y for x,y in zip(L1,L2)]
end_time = time.time()  # ← was missing

print("python list took :", end_time - start_time)

python list took : 0.6694972515106201


In [46]:
n1 = np.arange(size)
n2 = np.arange(size)

In [55]:
n3 = n1 + n2
n3
end_time = time.time()  # ← was missing
print("python numpy took :", end_time - start_time)

python numpy took : 46.893412351608276


In [8]:
rev_q1 = np.array([10,12,22])
print(rev_q1)
rev_q1.ndim

[10 12 22]


1

In [13]:
rev = np.array([[10,12,9],[47,46,46]])
rev.ndim
rev

array([[10, 12,  9],
       [47, 46, 46]])

In [17]:
rev[1,1]

(2, 3)

In [18]:
rev.dtype

dtype('int64')

In [19]:
rev.shape

(2, 3)

In [20]:
np.sort(rev)

array([[ 9, 10, 12],
       [46, 46, 47]])

In [3]:
import numpy as np

In [12]:
rev_1 = np.array([2,2,2])
rev_1

array([2, 2, 2])

In [6]:
arr1 = np.array([[12,34,45],[45,77,77]])
arr1

array([[12, 34, 45],
       [45, 77, 77]])

In [15]:
arr1

array([[12, 34, 45],
       [45, 77, 77]])

In [20]:
np.sort(arr1, axis=None)

array([12, 34, 45, 45, 77, 77])

In [27]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.arange(20,30,2)

array([20, 22, 24, 26, 28])

In [30]:
arr1.reshape(3,2)

array([[12, 34],
       [45, 45],
       [77, 77]])

In [35]:
print(arr1)

[[12 34 45]
 [45 77 77]]


In [33]:
arr1.min()

np.int64(12)

In [34]:
arr1.max()

np.int64(77)

In [37]:
arr1.sum(axis=1)

array([ 91, 199])

In [40]:
for row in arr1:
    print("row:-", row)

row:- [12 34 45]
row:- [45 77 77]


In [43]:
xx = np.array([1,4,16])
xx

array([ 1,  4, 16])

In [45]:
np.sqrt(xx)

array([1., 2., 4.])

In [46]:
np.square(xx)

array([  1,  16, 256])

In [55]:
np.std(xx)

np.float64(6.48074069840786)

In [24]:
from scipy import sparse

In [15]:
eye = np.eye(4)
print("Numpy array:\n".format(eye))
print(eye)

Numpy array:

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [25]:
A = int(input("Enter number A: "))
B = int(input("Enter number B: "))
C = int(input("Enter number C: "))

D = B * B - 4 * A * C

print("Discriminant =", D)

if D > 0:
    x1 = (-B + D**0.5) / (2 * A)
    x2 = (-B - D**0.5) / (2 * A)

    print("x1 =", x1)
    print("x2 =", x2)
elif D == 0:
    x = -B / (2 * A)
    print("x =", x)
else:
    print("no real solution")

Discriminant = -16
no real solution


In [2]:
import numpy as np

In [4]:
item = np.array([[12,33,5], [43,45,56]])
item

array([[12, 33,  5],
       [43, 45, 56]])

In [14]:
item[0,2] = 55
print(item)

[[12 33 55]
 [43 45 56]]


In [21]:
item.dtype

dtype('int64')

In [25]:
new_item = np.array([[12,13,14], [23,44,56]], dtype = float)
new_item.dtype

dtype('float64')

In [33]:
item.nbytes

48

In [34]:
item.itemsize
#8 byte storage

8

In [36]:
np.sort(item)

array([[12, 33, 55],
       [43, 45, 56]])

In [40]:
np.ones((2,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [46]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [49]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [61]:
np.linspace(10,20,4)

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [64]:
item.min()

np.int64(12)

In [65]:
item.max()

np.int64(56)

In [69]:
print(item)

[[12 33 55]
 [43 45 56]]


In [68]:
item.sum(axis=1)

array([100, 144])

In [74]:
jj = np.array([1,4,6,])
jj

array([1, 4, 6])

In [76]:
np.var(jj)

np.float64(4.222222222222222)