In [1]:
import numpy as np

In [3]:
a = np.array([6,7,8,9])
print(a)

[6 7 8 9]


In [6]:
a[0:2]

array([6, 7])

In [11]:
a[-2:]

array([8, 9])

In [12]:
b = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [14]:
b[0,1]

np.int64(2)

In [17]:
b[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [18]:
c = np.array([
    [101, 'Mira'],
    [102, 'Ram'],
    [103, 'Sam'],
    [104, 'John']
])

d = np.array([
    [101, 255, '2025-11-1'],
    [102, 150, '2026-1-1'],
    [103, 455, '2026-4-13'],
    [104, 500, '2026-6-12']
])

In [21]:
np.hstack((c,d))

array([['101', 'Mira', '101', '255', '2025-11-1'],
       ['102', 'Ram', '102', '150', '2026-1-1'],
       ['103', 'Sam', '103', '455', '2026-4-13'],
       ['104', 'John', '104', '500', '2026-6-12']], dtype='<U21')

In [26]:
e = np.array([
    [105, 'Venkat'],
    [106, 'David'],
    [107, 'Charles']
])


In [28]:
np.vstack((c,e))

array([['101', 'Mira'],
       ['102', 'Ram'],
       ['103', 'Sam'],
       ['104', 'John'],
       ['105', 'Venkat'],
       ['106', 'David'],
       ['107', 'Charles']], dtype='<U21')

In [34]:
Transactions = np.array([
    [101, 'Mira',255, '2025-11-1'],
    [102, 'Ram',150, '2026-1-1'],
    [103, 'Sam',455, '2026-4-13'],
    [104, 'John',500, '2026-6-12']])
print(Transactions)

[['101' 'Mira' '255' '2025-11-1']
 ['102' 'Ram' '150' '2026-1-1']
 ['103' 'Sam' '455' '2026-4-13']
 ['104' 'John' '500' '2026-6-12']]


In [36]:
np.hsplit(Transactions, [3]) #split from column three
#

[array([['101', 'Mira', '255'],
        ['102', 'Ram', '150'],
        ['103', 'Sam', '455'],
        ['104', 'John', '500']], dtype='<U21'),
 array([['2025-11-1'],
        ['2026-1-1'],
        ['2026-4-13'],
        ['2026-6-12']], dtype='<U21')]

In [1]:
import numpy as np

In [ ]:
arr = np.array[""]

In [4]:
ss = ["vatrad hemant vanlksr"]
type(ss)

list

In [7]:
s(1)

NameError: name 's' is not defined